name: Deploy iban.bio App

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  command_timeout: 30m
                  script: |
                      # 1. NVM'i ve Node'u manuel olarak yükle (En garanti yöntem)
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

                      # 2. Herhangi bir komut hata verirse işlemi anında durdur
                      set -e

                      echo "🚀 Deployment basliyor..."

                      cd /home/ubuntu/iban-bio-app

                      echo "⬇️ Git pull yapiliyor..."
                      git pull origin main

                      echo "📦 Paketler yükleniyor..."
                      yarn install

                      rm -rf .next

                      echo "🏗️ Build aliniyor (Bu islem biraz sürebilir)..."
                      # Swap alanı sayesinde burada donmayacaktır
                      yarn build

                      echo "🔄 PM2 Reload yapiliyor..."
                      # Restart yerine reload kullanırsan kesinti olmaz (Zero Downtime)
                      pm2 restart 1

                      echo "✅ Deployment basariyla tamamlandi!"
